name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-pr:
    name: Lint PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert

  check-files:
    name: Check for sensitive files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for .env files
        run: |
          if find . -name ".env" -not -path "./node_modules/*" | grep -q .; then
            echo "Error: .env file found in repository"
            exit 1
          fi

      - name: Check for sensitive patterns
        run: |
          if grep -r "API_KEY\|SECRET\|PASSWORD\|TOKEN" --include="*.js" --include="*.ts" --exclude-dir=node_modules --exclude-dir=.git .; then
            echo "Warning: Potential sensitive data found. Please review."
          fi

  validate-code:
    name: Validate Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter with annotations
        run: npm run lint

      - name: Check code formatting
        run: |
          if command -v npx prettier &> /dev/null; then
            npx prettier --check "**/*.{js,json,md}"
          fi

  test-coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Comment PR with coverage
        uses: romeovs/lcov-reporter-action@v0.3.1
        if: github.event_name == 'pull_request'
        with:
          lcov-file: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
